name: CI

on: [push, pull_request]

env:
  BUILD_DIR: _build
  PIP_PACKAGES: >-
    meson!=1.8.0
    cmake
    ninja
    gcovr
  PIP_EXTRAS: >-
    pkgconfig
    pytest
    pytest-cov
    cffi
    numpy
    ase
    matplotlib
    qcelemental

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        build-type: [debug]
        toolchain:
          - {compiler: gcc, version: '12', build: meson}
          - {compiler: gcc, version: '12', build: cmake}

        include:
          - os: ubuntu-latest
            build-type: coverage
            toolchain: {compiler: gcc, version: '10', build: meson}

          - os: ubuntu-latest
            build-type: debug
            toolchain: {compiler: gcc, version: '11', build: meson}

          - os: ubuntu-latest
            build-type: debug
            toolchain: {compiler: gcc, version: '13', build: meson}

          - os: ubuntu-latest
            build-type: debug
            toolchain: {compiler: gcc, version: '14', build: meson}

          - os: ubuntu-latest
            build-type: debug
            toolchain: {compiler: intel-classic, version: '2021.2', mkl_version: '2021.2.0', build: meson}

          - os: ubuntu-latest
            build-type: debug
            toolchain: {compiler: intel, version: '2024.1', mkl_version: '2024.1', build: meson}

          - os: ubuntu-latest
            build-type: debug
            toolchain: {compiler: intel, version: '2025.1', mkl_version: '2025.1', build: meson}

          - os: ubuntu-latest
            build-type: debug
            toolchain: {compiler: gcc, version: '12', build: fpm}

          - os: macos-15-intel
            build-type: debug
            toolchain: {compiler: gcc, version: '12', build: meson}

          - os: windows-latest
            build-type: debug
            toolchain: {compiler: gcc, version: '12', build: meson}
            msystem: MINGW64
            arch: x86_64

          - os: ubuntu-latest
            build-type: release
            toolchain: {compiler: gcc, version: '12', build: meson}

          - os: macos-latest
            build-type: release
            toolchain: {compiler: gcc, version: '12', build: meson}

          - os: windows-latest
            build-type: release
            toolchain: {compiler: gcc, version: '12', build: meson}
            msystem: MINGW64
            arch: x86_64

    defaults:
      run:
        shell: bash

    env:
      PYTHON_V: 3.9

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      if: ${{ !contains(matrix.os, 'windows') }}
      with:
        python-version: ${{ env.PYTHON_V }}

    - name: Setup MSYS2 toolchain (Windows)
      if: ${{ contains(matrix.os, 'windows') }}
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.msystem }}
        update: false
        install: >-
          git
          mingw-w64-${{ matrix.arch }}-gcc-fortran
          mingw-w64-${{ matrix.arch }}-lapack
          mingw-w64-${{ matrix.arch }}-python
          mingw-w64-${{ matrix.arch }}-python-pip
          mingw-w64-${{ matrix.arch }}-meson
          mingw-w64-${{ matrix.arch }}-ninja
          mingw-w64-${{ matrix.arch }}-binutils
          mingw-w64-${{ matrix.arch }}-pkg-config
          xz

    - name: Install compiler (setup-fortran)
      if: ${{ matrix.toolchain.compiler == 'gcc' || (contains(matrix.os, 'ubuntu') && contains(matrix.toolchain.compiler, 'intel')) }}
      uses: fortran-lang/setup-fortran@v1
      with:
        compiler: ${{ matrix.toolchain.compiler == 'gcc' && 'gcc' || matrix.toolchain.compiler }}
        version: ${{ matrix.toolchain.version }}

    - name: Install LAPACK (macOS)
      if: ${{ contains(matrix.os, 'macos') && matrix.toolchain.compiler == 'gcc' }}
      run: |
        brew install openblas
        echo "PKG_CONFIG_PATH=$(brew --prefix openblas)/lib/pkgconfig" >> $GITHUB_ENV
        echo "LDFLAGS=-L$(brew --prefix openblas)/lib" >> $GITHUB_ENV
        echo "CPPFLAGS=-I$(brew --prefix openblas)/include" >> $GITHUB_ENV

    - name: Install LAPACK (Linux)
      if: ${{ contains(matrix.os, 'ubuntu') && matrix.toolchain.compiler == 'gcc' }}
      run: |
        sudo apt-get update
        sudo apt-get install -y liblapack-dev

    - name: Install fpm
      if: ${{ matrix.toolchain.build == 'fpm' }}
      uses: fortran-lang/setup-fpm@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Prepare for cache restore
      if: ${{ contains(matrix.toolchain.compiler, 'intel') }}
      run: |
        sudo mkdir -p /opt/intel
        sudo chown $USER /opt/intel

    - name: Cache Intel installation
      if: ${{ contains(matrix.toolchain.compiler, 'intel') }}
      id: cache-install
      uses: actions/cache@v4
      with:
        path: /opt/intel/oneapi
        key: install-${{ matrix.toolchain.compiler }}-${{ matrix.toolchain.version }}-${{ matrix.toolchain.mkl_version }}-${{ matrix.os }}

    - name: Install Intel MKL
      if: ${{ contains(matrix.os, 'ubuntu') && contains(matrix.toolchain.compiler, 'intel') && steps.cache-install.outputs.cache-hit != 'true' }}
      run: |
        sudo apt-get install intel-oneapi-mkl-${{ matrix.toolchain.mkl_version }} intel-oneapi-mkl-devel-${{ matrix.toolchain.mkl_version }}

    - name: Setup Intel oneAPI environment
      if: ${{ contains(matrix.toolchain.compiler, 'intel') }}
      run: |
        source /opt/intel/oneapi/setvars.sh --force
        printenv >> $GITHUB_ENV

    - name: Install build and test dependencies
      if: ${{ !contains(matrix.os, 'windows') }}
      run: python -m pip install ${{ env.PIP_PACKAGES }} ${{ env.PIP_EXTRAS }}

    - name: Configure build (meson)
      if: ${{ matrix.toolchain.build == 'meson' && !contains(matrix.os, 'windows') }}
      run: >-
        meson setup ${{ env.BUILD_DIR }}
        --buildtype=${{ matrix.build-type == 'coverage' && 'debug' || matrix.build-type }}
        --prefix=$PWD/_dist
        --libdir=lib
        --warnlevel=0
        -Db_coverage=${{ matrix.build-type == 'coverage' }}
        ${{ env.MESON_ARGS }}
      env:
        MESON_ARGS: >-
          ${{ contains(matrix.toolchain.compiler, 'intel') && '-Dfortran_link_args=-qopenmp -Dapi=false' || '' }}
          ${{ contains(matrix.os, 'macos') && '-Dlapack=openblas' || '' }}

    - name: Configure build (meson, Windows/MSYS2)
      if: ${{ matrix.toolchain.build == 'meson' && contains(matrix.os, 'windows') }}
      shell: msys2 {0}
      run: >-
        meson setup ${{ env.BUILD_DIR }}
        --buildtype=${{ matrix.build-type }}
        --prefix="$PWD/_dist"
        --libdir=lib
        --warnlevel=0
        -Dlapack=netlib
        -Db_coverage=false
        -Dfortran_link_args=-Wl,--allow-multiple-definition
      env:
        CC: gcc
        FC: gfortran

    - name: Configure build (CMake)
      if: ${{ matrix.toolchain.build == 'cmake' }}
      run: >-
        cmake -B${{ env.BUILD_DIR }}
        -GNinja
        -DCMAKE_BUILD_TYPE=Debug
        -DCMAKE_INSTALL_PREFIX=$PWD/_dist
        -DCMAKE_INSTALL_LIBDIR=lib

    - name: Build library (fpm)
      if: ${{ matrix.toolchain.build == 'fpm' }}
      run: |
        fpm --version
        fpm build

    - name: Build library
      if: ${{ matrix.toolchain.build != 'fpm' && !contains(matrix.os, 'windows') }}
      run: ninja -C ${{ env.BUILD_DIR }}

    - name: Build library (Windows/MSYS2)
      if: ${{ matrix.toolchain.build != 'fpm' && contains(matrix.os, 'windows') }}
      shell: msys2 {0}
      run: ninja -C ${{ env.BUILD_DIR }}

    - name: Run unit tests (fpm)
      if: ${{ matrix.toolchain.build == 'fpm' }}
      run: fpm test

    - name: Run unit tests (meson)
      if: ${{ matrix.toolchain.build == 'meson' && !contains(matrix.os, 'windows') }}
      run: >-
        meson test
        -C ${{ env.BUILD_DIR }}
        --print-errorlogs
        --no-rebuild
        --num-processes 1
        --suite tblite
        -t 2
      env:
        OMP_NUM_THREADS: 1,2,1

    - name: Run unit tests (meson, Windows/MSYS2)
      if: ${{ matrix.toolchain.build == 'meson' && contains(matrix.os, 'windows') }}
      shell: msys2 {0}
      run: >-
        meson test
        -C ${{ env.BUILD_DIR }}
        --print-errorlogs
        --no-rebuild
        --num-processes 1
        --suite tblite
        -t 120
      env:
        OMP_NUM_THREADS: 1

    - name: Run benchmarks
      if: ${{ matrix.toolchain.build == 'meson' && matrix.build-type == 'debug' && !contains(matrix.os, 'windows') }}
      run: >-
        meson test
        -C ${{ env.BUILD_DIR }}
        --print-errorlogs
        --no-rebuild
        --num-processes 1
        --suite tblite
        -t 2
        --benchmark

    - name: Run unit tests (ctest)
      if: ${{ matrix.toolchain.build == 'cmake' }}
      run: |
        ctest --output-on-failure --parallel 2 -R '^tblite/'
      working-directory: ${{ env.BUILD_DIR }}
      env:
        OMP_NUM_THREADS: 1,2,1

    - name: Create coverage report
      if: ${{ matrix.toolchain.build == 'meson' && matrix.build-type == 'coverage' }}
      run: |
        ninja -C ${{ env.BUILD_DIR }} coverage

    - name: Install project
      if: ${{ matrix.toolchain.build != 'fpm' && !contains(matrix.os, 'windows') }}
      run: |
        ninja -C ${{ env.BUILD_DIR }} install
        echo "TBLITE_PREFIX=$PWD/_dist" >> $GITHUB_ENV

    - name: Install project (Windows/MSYS2)
      if: ${{ matrix.toolchain.build != 'fpm' && contains(matrix.os, 'windows') }}
      shell: msys2 {0}
      run: |
        ninja -C ${{ env.BUILD_DIR }} install
        echo "TBLITE_PREFIX=$PWD/_dist" >> $GITHUB_ENV

    - name: Create package
      if: ${{ matrix.toolchain.build == 'meson' && matrix.build-type == 'debug' && matrix.toolchain.compiler == 'gcc' && matrix.toolchain.version == '12' && !contains(matrix.os, 'windows') }}
      run: |
        tar cvf ${{ env.OUTPUT }} _dist
        xz -T0 ${{ env.OUTPUT }}
        echo "TBLITE_OUTPUT=${{ env.OUTPUT }}.xz" >> $GITHUB_ENV
      env:
        OUTPUT: tblite-${{ matrix.toolchain.compiler }}-${{ matrix.toolchain.version }}-${{ matrix.os }}.tar

    - name: Create package (Windows/MSYS2)
      if: ${{ matrix.toolchain.build == 'meson' && matrix.build-type == 'debug' && matrix.toolchain.compiler == 'gcc' && matrix.toolchain.version == '12' && contains(matrix.os, 'windows') }}
      shell: msys2 {0}
      run: |
        tar cvf ${{ env.OUTPUT }} _dist
        xz -T0 ${{ env.OUTPUT }}
        echo "TBLITE_OUTPUT=${{ env.OUTPUT }}.xz" >> $GITHUB_ENV
      env:
        OUTPUT: tblite-${{ matrix.toolchain.compiler }}-${{ matrix.toolchain.version }}-${{ matrix.os }}.tar

    - name: Upload package
      if: ${{ matrix.toolchain.build == 'meson' && matrix.build-type == 'debug' && matrix.toolchain.compiler == 'gcc' && matrix.toolchain.version == '12' }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.TBLITE_OUTPUT }}
        path: ${{ env.TBLITE_OUTPUT }}

    - name: Upload coverage report
      if: ${{ matrix.toolchain.build == 'meson' && matrix.build-type == 'coverage' }}
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

  python:
    needs:
      - build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        gcc_v: ['12']
        python_v: ['3.9', '3.10', '3.11', '3.12', '3.13']

        include:
          - os: macos-latest
            gcc_v: '12'
            python_v: '3.12'

          - os: macos-15-intel
            gcc_v: '12'
            python_v: '3.12'

          - os: windows-latest
            gcc_v: '12'
            python_v: '3.12'
            msystem: MINGW64
            arch: x86_64

    env:
      OMP_NUM_THREADS: 2,1
      TBLITE_OUTPUT: tblite-gcc-${{ matrix.gcc_v }}-${{ matrix.os }}.tar.xz

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      if: ${{ !contains(matrix.os, 'windows') }}
      with:
        python-version: ${{ matrix.python_v }}

    - name: Setup MSYS2 (Windows)
      if: ${{ contains(matrix.os, 'windows') }}
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.msystem }}
        update: false
        path-type: minimal
        install: >-
          git
          mingw-w64-${{ matrix.arch }}-gcc-fortran
          mingw-w64-${{ matrix.arch }}-lapack
          mingw-w64-${{ matrix.arch }}-pkg-config
          mingw-w64-${{ matrix.arch }}-python
          mingw-w64-${{ matrix.arch }}-python-pip
          mingw-w64-${{ matrix.arch }}-python-numpy
          mingw-w64-${{ matrix.arch }}-python-cffi
          mingw-w64-${{ matrix.arch }}-python-pytest
          mingw-w64-${{ matrix.arch }}-python-pytest-cov
          mingw-w64-${{ matrix.arch }}-python-pkgconfig
          mingw-w64-${{ matrix.arch }}-python-matplotlib
          mingw-w64-${{ matrix.arch }}-python-certifi
          mingw-w64-${{ matrix.arch }}-python-scipy
          mingw-w64-${{ matrix.arch }}-python-pydantic
          mingw-w64-${{ matrix.arch }}-meson
          mingw-w64-${{ matrix.arch }}-ninja
          ca-certificates
          xz

    - name: Install GCC Compiler (setup-fortran)
      if: ${{ !contains(matrix.os, 'windows') }}
      uses: fortran-lang/setup-fortran@v1
      with:
        compiler: gcc
        version: ${{ matrix.gcc_v }}

    - name: Link LAPACK (macOS)
      if: ${{ contains(matrix.os, 'macos') }}
      run: |
        brew install openblas
        echo "PKG_CONFIG_PATH=$(brew --prefix openblas)/lib/pkgconfig" >> $GITHUB_ENV
        echo "LDFLAGS=-L$(brew --prefix openblas)/lib" >> $GITHUB_ENV
        echo "CPPFLAGS=-I$(brew --prefix openblas)/include" >> $GITHUB_ENV

    - name: Install LAPACK (Linux)
      if: ${{ contains(matrix.os, 'ubuntu') }}
      run: |
        sudo apt-get update
        sudo apt-get install -y libblas-dev liblapack-dev

    - name: Install test dependencies
      if: ${{ !contains(matrix.os, 'windows') }}
      run: |
        python -m pip install --upgrade pip
        python -m pip install ${{ env.PIP_EXTRAS }} meson-python

    - name: Create venv + extra deps (Windows/MSYS2)
      if: ${{ contains(matrix.os, 'windows') }}
      shell: msys2 {0}
      run: |
        set -eux
        python -m venv --system-site-packages .venv
        source .venv/bin/activate

        SSL_CERT_FILE="$(python -c 'import certifi; print(certifi.where())')"
        export SSL_CERT_FILE
        echo "SSL_CERT_FILE=$SSL_CERT_FILE" >> "$GITHUB_ENV"

        python -m pip install -U pip setuptools wheel

        # Needed so the pyproject build backend "mesonpy" can be imported
        python -m pip install pyproject-metadata

        # qcelemental runtime dep (pure python, quick)
        python -m pip install pint

        # Keep deps disabled for the big packages to avoid builds
        python -m pip install --no-deps ase qcelemental meson-python

    - name: Download package
      uses: actions/download-artifact@v4
      with:
        name: ${{ env.TBLITE_OUTPUT }}

    - name: Unpack package
      if: ${{ !contains(matrix.os, 'windows') }}
      run: |
        tar xvf ${{ env.TBLITE_OUTPUT }}
        echo "TBLITE_PREFIX=$PWD/_dist" >> $GITHUB_ENV

    - name: Unpack package (Windows/MSYS2)
      if: ${{ contains(matrix.os, 'windows') }}
      shell: msys2 {0}
      run: |
        tar xvf ${{ env.TBLITE_OUTPUT }}
        echo "TBLITE_PREFIX=$PWD/_dist" >> $GITHUB_ENV

    - name: Install Python extension module (pip)
      if: ${{ !contains(matrix.os, 'windows') }}
      working-directory: python
      run: python -m pip install . --user
      env:
        PKG_CONFIG_PATH: ${{ env.PKG_CONFIG_PATH }}:${{ env.TBLITE_PREFIX }}/lib/pkgconfig

    - name: Install Python extension module (Windows/MSYS2)
      if: ${{ contains(matrix.os, 'windows') }}
      shell: msys2 {0}
      working-directory: python
      run: |
        set -eux
        source ../.venv/bin/activate
        PKG_CONFIG_PATH="${PKG_CONFIG_PATH}:${TBLITE_PREFIX}/lib/pkgconfig" python -m pip install . --no-build-isolation

    - name: Test Python API
      if: ${{ !contains(matrix.os, 'windows') }}
      run: |
        if [[ "${RUNNER_OS}" == "macOS" ]]; then
          export DYLD_LIBRARY_PATH="${TBLITE_PREFIX}/lib:${DYLD_LIBRARY_PATH}"
        else
          export LD_LIBRARY_PATH="${TBLITE_PREFIX}/lib:${LD_LIBRARY_PATH}"
        fi
        pytest --pyargs tblite --cov=tblite -vv

    - name: Test Python API (Windows/MSYS2)
      if: ${{ contains(matrix.os, 'windows') }}
      shell: msys2 {0}
      run: |
        set -eux
        source .venv/bin/activate
        export PATH="${TBLITE_PREFIX}/bin:${TBLITE_PREFIX}/lib:${PATH}"
        python -m pytest --pyargs tblite --cov=tblite -vv

    - name: Upload coverage report
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
